import subprocess
import sys, os, json, requests
import time
import math
import logging

import pandas as pd
import numpy as np
from datetime import datetime
from dotenv import load_dotenv
from pathlib import Path
from zoneinfo import ZoneInfo

from fastapi.responses import JSONResponse
import warnings
warnings.filterwarnings("ignore", category=pd.errors.SettingWithCopyWarning)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)

load_dotenv()
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
FOLDER_PATH_DB_EARLYBIRD = os.path.join(BASE_DIR, "DB-EB")
FOLDER_PATH_DB_LASTMINUTE = os.path.join(BASE_DIR, "DB-LM")
FOLDER_PATH_ROUTINE_EARLYBIRD = os.path.join(BASE_DIR, "Routine-EB")
FOLDER_PATH_ROUTINE_LASTMINUTE = os.path.join(BASE_DIR, "Routine-LM")
TOKEN_KEY = os.getenv('TOKEN_SERVER')
PREDICTIVE_DATA_HOOK_URL = os.getenv('PREDICTIVE_DATA_HOOK_URL')
WEBHOOK_URL = "https://2f68b6cd-a59f-4429-af46-00f19a73248e.mock.pstmn.io/webhook"


def sanitize_nans(obj):
    """Recursively replace NaN/Inf with None for JSON compliance."""
    if isinstance(obj, float) and (math.isnan(obj) or math.isinf(obj)):
        return None
    elif isinstance(obj, dict):
        return {k: sanitize_nans(v) for k, v in obj.items()}
    elif isinstance(obj, list):
        return [sanitize_nans(v) for v in obj]
    return obj

def chartjs_to_endpoint(data, customer_id, error_msg=None, use_company_api=True):
    print("Try sending!!!")
    try:
        if use_company_api:
            url_adr = PREDICTIVE_DATA_HOOK_URL
            headers = {"Content-Type": "application/json",
                       "Authorization": f"Bearer {TOKEN_KEY}"}
            # response = requests.post(WEBHOOK_URL, headers=headers, data=json.dumps(data))

        else:
            url_adr = WEBHOOK_URL
            headers = {
                "Content-Type": "application/json"
            }

        response = requests.post(url=url_adr, headers=headers, json=data)
        # response = requests.post(url, headers=headers, json=data)
        date_format_save = datetime.now(ZoneInfo('Asia/Makassar')).strftime('%Y-%m-%d')
        with open(f"internal_logger_{date_format_save}.txt", 'a') as f:
            if len(data) > 0:
                f.write("Adaptive Pipeline ")
                f.write(f"Date: {datetime.now(ZoneInfo('Asia/Makassar')).strftime('%Y-%m-%d %H:%M:%S')} ")
                f.write(f"Property ID: {customer_id}")
                f.write("\nStatus: SENT. DATA NOT BLANK.\n")
            elif len(data) == 0:
                f.write("Adaptive Pipeline ")
                f.write(f"Date: {datetime.now(ZoneInfo('Asia/Makassar')).strftime('%Y-%m-%d %H:%M:%S')} ")
                f.write(f"Property ID: {customer_id}")
                f.write("\nStatus: SENT. DATA BLANK OR ERROR OCCURED.\n")
                if error_msg:
                    f.write(f"Error due to : {error_msg}")

        # For debugging
        if response.status_code == 200:
            print("ChartJS successfully sent!")
        else:
            print(f"Failed to send data. Status: {response.status_code}, Response: {response.text}")
        return response.status_code
    except Exception as e:
        print(f"Error sending ChartJS: {e}")
        raise

def read_all_json(folder_loc, flag):
    if not os.path.exists(folder_loc):
        os.makedirs(folder_loc, exist_ok=True)
        return pd.DataFrame()
    
    tempo_df = pd.DataFrame()
    files_to_delete = []

    for filename in os.listdir(folder_loc):
        if not filename.lower().endswith(".json"):
            continue
            
        join_name = os.path.join(folder_loc, filename)
        try:
            with open(join_name, "r") as f:
                interest_data = json.load(f)
            
            # Handle possible nested 'result' key if generated by error/fallback handlers
            if "result" in interest_data and isinstance(interest_data["result"], list) and len(interest_data["result"]) > 0:
                interest_data = interest_data["result"][0]

            forecasts = interest_data.get("forecasts", [])
            cust_id = interest_data.get("customer_id")
            currency_id = interest_data.get("currency_id", "")

            if not forecasts or cust_id is None:
                logging.warning(f"File {filename} contains no forecasts or missing customer_id. Skipping.")
                files_to_delete.append(join_name)
                continue

            df_routine = pd.DataFrame(forecasts)
            
            # Verify required columns exist
            required_cols = {"room_type_id", "forecast_date"}
            if not required_cols.issubset(df_routine.columns):
                logging.warning(f"File {filename} missing required forecast columns: {required_cols - set(df_routine.columns)}. Skipping.")
                files_to_delete.append(join_name)
                continue

            df_routine["flag"] = flag
            df_routine["customer_id"] = cust_id
            df_routine["currency_id"] = currency_id
            df_routine["_source"] = 1

            tempo_df = pd.concat([tempo_df, df_routine], ignore_index=True)
            files_to_delete.append(join_name)

        except Exception as err:
            logging.error(f"Failed to process {filename}: {err}")
            continue

    # Delete only files that were successfully processed or handled
    for filepath in files_to_delete:
        try:
            os.remove(filepath)
        except OSError as e:
            logging.warning(f"Could not remove {filepath}: {e}")

    if len(tempo_df) > 0:
        return tempo_df
    else:
        print("No DataFrame Created")
        return tempo_df
        
def main():
    try: 
        need_to_send = False
        while True:  
            # It will be continuous loop in which:
            # 1. Read JSON files from routine loop and put it inside dataframe
            # to overwrite it and save it
            # 2. Read JSON file from overtaking job and put it inside dataframe
            # to overwrite it and save it
            # 3. Send the DataFrame as JSON and send it
            if not os.path.exists("master_database.pkl"):
                print("Database master not exist, creating first database.")
                master_df = pd.DataFrame()
            else:
                print("Database exist, load up data..")
                master_df = pd.read_pickle("master_database.pkl")

            # We start with step one
            print("Looking for Routine Earlybird data.")
            save_path_loc = os.path.join(FOLDER_PATH_ROUTINE_EARLYBIRD)
            extracted_df = read_all_json(save_path_loc, 1)
            if len(extracted_df) > 0:
                need_to_send = True
                print("Routine Earlybird data exist.")
                master_df = pd.concat([master_df, extracted_df])
                master_df = master_df.sort_values(["flag", "_source"], ascending=[True, True]).drop_duplicates(subset=["customer_id", "room_type_id", "forecast_date"], keep="last").reset_index(drop=True)
            # flag 1 itu prioritas rendah, 2 itu prioritas untuk Early Bird dan 3 itu untuk Last Minute

            print("Looking for Routine Last Minute data.")
            save_path_loc = os.path.join(FOLDER_PATH_ROUTINE_LASTMINUTE)
            extracted_df = read_all_json(save_path_loc, 2)
            if len(extracted_df) > 0:
                need_to_send = True
                print("Routine Last Minute data exist.")
                master_df = pd.concat([master_df, extracted_df])
                master_df = master_df.sort_values(["flag", "_source"], ascending=[True, True]).drop_duplicates(subset=["customer_id", "room_type_id", "forecast_date"], keep="last").reset_index(drop=True)

            # Then we continue on step 2
            print("Looking for urgent Early Bird Database.")
            save_path_loc = os.path.join(FOLDER_PATH_DB_EARLYBIRD)
            extracted_df = read_all_json(save_path_loc, 3)
            if len(extracted_df) > 0:
                need_to_send = True
                print("Urgent Early Bird data exist.")
                master_df = pd.concat([master_df, extracted_df])
                master_df = master_df.sort_values(["flag", "_source"], ascending=[True, True]).drop_duplicates(subset=["customer_id", "room_type_id", "forecast_date"], keep="last").reset_index(drop=True)

            print("Looking for urgent Last Minute Database.")
            save_path_loc = os.path.join(FOLDER_PATH_DB_LASTMINUTE)
            extracted_df = read_all_json(save_path_loc, 4)
            if len(extracted_df) > 0:
                need_to_send = True
                print("Urgent Last Minute data exist.")
                master_df = pd.concat([master_df, extracted_df])
                master_df = master_df.sort_values(["flag", "_source"], ascending=[True, True]).drop_duplicates(subset=["customer_id", "room_type_id", "forecast_date"], keep="last").reset_index(drop=True)
            
            master_df["_source"] = 0 # flag it to old data so it can be overwrite next

            # SAVE YOUR DATAFRAME!!!
            print("Overwriting Dataframe to saved file")
            master_df.to_pickle("master_database.pkl")

            # SEND THE DATAFRAME TO SERVER
            print("Sending the dataframe to server")
            master_df = master_df.sort_values("customer_id", ascending=True)

            presentation_charts = {
                "model_version": "v1.0.0",
                "customer_id": "",
                "currency_id": "",
                "forecasts": []
            }
            print(f"Total customer : {len(master_df['customer_id'].unique())}")
            if need_to_send == True:
                for i in master_df["customer_id"].unique():
                    highlight_df = master_df[master_df["customer_id"] == i]
                    highlight_df["room_type_id"] = highlight_df["room_type_id"].astype(int)
                    highlight_df = highlight_df.sort_values("room_type_id", ascending=True)

                    id_storage = i
                    curr_id_storage = highlight_df["currency_id"].iloc[0]

                    highlight_df = highlight_df.drop(columns=["customer_id", "currency_id", "flag", "_source"])
                    highlight_df = highlight_df.fillna(0)
                    presentation_charts_copy = presentation_charts.copy()
                    interest_json = highlight_df.to_dict(orient="records")
                    presentation_charts_copy["customer_id"] = id_storage
                    presentation_charts_copy["currency_id"] = curr_id_storage
                    presentation_charts_copy["forecasts"] = interest_json
                    
                    for item in presentation_charts_copy["forecasts"]:
                        if "property_id" in item:
                            item["property_id"] = int(item["property_id"])
                            
                    chartjs_to_endpoint(sanitize_nans(presentation_charts_copy["forecasts"]), id_storage)
                    time.sleep(3)
                need_to_send = False
            if need_to_send == False:
                break # Karena ada CRON job, setelah ngirim kita close loop dan terminate execution
            time.sleep(300)

    except Exception as e:
        error_summary = f"{type(e).__name__}: {e}"
        print(error_summary)
        return error_summary

if __name__ == "__main__":
    main()
